version: '3.5'
services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9001:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - stronghold

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Password111
      PGDATA: /data/postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/data/postgres
    ports:
      - 5432:5432

# This is an example of microservice using nginx Dockerfile
  sc-client:
    container_name: sourcecontrol-client
    build:
      context: ../frontend
      dockerfile: apps/source-control/Dockerfile
    restart: unless-stopped
    ports:
      - 8086:80
    networks:
      - stronghold
    depends_on:
      - sourcecontrol

# This is an example of springboot service: https://www.appsdeveloperblog.com/spring-boot-microservices-deployment-with-docker-compose/
  sourcecontrol:
    container_name: sourcecontrol
    image: sourcecontrol
    build:
      context: ../backend/sourcecontrol
      dockerfile: Dockerfile
    ports:
      - 8085:8080
    restart: unless-stopped
    depends_on:
      - postgres

  vista:
    image: mringive/symbolguys-stronghold-vista:latest
    container_name: vista
    restart: unless-stopped
    ports:
      - 3000:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - stronghold
    depends_on:
      - portainer
      - manor

  manor:
    image: mringive/symbolguys-stronghold-manor:latest
    container_name: manor
    restart: unless-stopped
    ports:
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - stronghold
    depends_on:
      - portainer

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres-data:
    driver: local
  portainer-data:
    external: false

networks:
  stronghold:
