version: '3.5'
services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9001:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    networks:
      - stronghold

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: Password111
      PGDATA: /data/postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/data/postgres
    ports:
      - 5432:5432

# This is an example of microservice using nginx Dockerfile
  microfrontend-example:
    profiles:
      - donotstart
    container_name: microfrontend-example
    build:
      context: ../frotend/apps/stronghold
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - stronghold
    depends_on:
      - postgres

# This is an example of springboot service: https://www.appsdeveloperblog.com/spring-boot-microservices-deployment-with-docker-compose/
  sourcecontrol:
    container_name: sourcecontrol
    image: sourcecontrol
    build:
      context: ../backend/sourcecontrol
      dockerfile: Dockerfile
    ports:
      - 8085:8080
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - 'spring.r2dbc.url=r2dbc:postgresql://postgres:5432/mydatabase'
      - 'spring.r2dbc.username=sa'
      - 'spring.r2dbc.password=Password111'
      - 'spring.r2dbc.pool.max-size=10'
      - 'spring.jpa.hibernate.ddl-auto=create'
      - 'spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true'
      - 'spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect'

  vista:
    image: mringive/symbolguys-stronghold-vista:latest
    container_name: vista
    restart: unless-stopped
    ports:
      - 3000:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - stronghold
    depends_on:
      - portainer

  manor:
    image: mringive/symbolguys-stronghold-manor:latest
    container_name: manor
    restart: unless-stopped
    ports:
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - stronghold
    depends_on:
      - portainer

volumes:
  postgres-data:
    driver: local
  portainer-data:
    external: false

networks:
  stronghold:
